[server]
# Automatically rerun script when the file is modified on disk.
runOnSave = true

[theme]
primaryColor="#1f9be4"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

